shows:
  self-hosted:
    fireside_url: https://selfhosted.show
    fireside_slug: selfhosted
    jb_url: https://www.jupiterbroadcasting.com/show/self-hosted
    acronym: SSH
    name: Self-Hosted
  coder-radio:
    fireside_url: https://coder.show
    fireside_slug: coderradio
    jb_url: https://www.jupiterbroadcasting.com/show/coderradio
    acronym: CR
    name: Coder Radio
  linux-action-news:
    fireside_url: https://linuxactionnews.com
    fireside_slug: linuxactionnews
    jb_url: https://www.jupiterbroadcasting.com/show/linux-action-news
    acronym: LAN
    name: Linux Action News
  linux-unplugged:
    fireside_url: https://linuxunplugged.com
    fireside_slug: linuxunplugged
    jb_url: https://www.jupiterbroadcasting.com/show/linuxun
    acronym: LUP
    name: LINUX Unplugged
  extras:
    fireside_url: https://extras.show
    fireside_slug: extras
    jb_url: https://www.jupiterbroadcasting.com/show/extras
    acronym: JE
    name: Jupiter EXTRAS
  office-hours:
    fireside_url: https://www.officehours.hair
    fireside_slug: office
    jb_url: https://www.jupiterbroadcasting.com/show/office
    acronym: OH
    name: Office Hours
# Map usernames of hosts/guests as they appear in fireside to how we want to save them
usernames_map:
  chrislas: chris
  wespayne: wes
  alexktz: alex
  brentgervais: brent